{{- if .Values.adcs.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adcs.credentials.name | default (printf "%s-credentials" (include "adcs-issuer.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adcs-issuer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  username: {{ .Values.adcs.credentials.username | b64enc | quote }}
  password: {{ .Values.adcs.credentials.password | b64enc | quote }}
{{- end }}
