apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "adcs-issuer.fullname" . }}-manager
  labels:
    {{- include "adcs-issuer.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - adcs.certmanager.lcwsre.io
    resources:
      - adcsissuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - adcs.certmanager.lcwsre.io
    resources:
      - adcsissuers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - adcs.certmanager.lcwsre.io
    resources:
      - adcsrequests
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - adcs.certmanager.lcwsre.io
    resources:
      - adcsrequests/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - adcs.certmanager.lcwsre.io
    resources:
      - clusteradcsissuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - adcs.certmanager.lcwsre.io
    resources:
      - clusteradcsissuers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests/status
    verbs:
      - get
      - patch
      - update
