apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "adcs-issuer.fullname" . }}-manager
  labels:
    {{- include "adcs-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "adcs-issuer.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "adcs-issuer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
