{{- if .Values.imageCredentials.create }}
{{- if not .Values.imageCredentials.registry }}
{{- fail "imageCredentials.registry is required when imageCredentials.create is true" }}
{{- end }}
{{- if not .Values.imageCredentials.username }}
{{- fail "imageCredentials.username is required when imageCredentials.create is true" }}
{{- end }}
{{- if not .Values.imageCredentials.password }}
{{- fail "imageCredentials.password is required when imageCredentials.create is true" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-registry" (include "adcs-issuer.fullname" .)) .Values.imageCredentials.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adcs-issuer.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.imageCredentials.registry .Values.imageCredentials.username .Values.imageCredentials.password (default "" .Values.imageCredentials.email) (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
{{- end }}
